package ajahn.dhsn.acid_frog.data.database.entity

import ajahn.dhsn.acid_frog.domain.model.AppProfile
import androidx.compose.runtime.mutableStateOf
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Entity class representing a user profile in the database.
 *
 * This class maps to the "profiles" table and includes fields for unique identification,
 * user name, allergens, and activity status.
 *
 * @property id The unique identifier for the profile. Auto-generated by the database.
 * @property name The name of the user.
 * @property allergens A list of allergens associated with the user.
 * @property isActive Indicates whether the profile is currently active.
 */
@Entity(tableName = "profiles")
data class ProfileEntity(
    @PrimaryKey(autoGenerate = true) val id: Long,
    val name: String,
    val allergens: List<String>,
    val isActive: Boolean
) {
    companion object {
        /**
         * Converts an [AppProfile] to a [ProfileEntity].
         *
         * @param appProfile The [AppProfile] to convert.
         * @return A new [ProfileEntity] instance populated with data from [appProfile].
         */
        fun fromAppProfile(
            appProfile: AppProfile
        ): ProfileEntity {
            return ProfileEntity(
                id = appProfile.id.value,
                name = appProfile.name.value,
                allergens = appProfile.allergens,
                isActive = appProfile.isActive.value,
            )
        }
    }
}

/**
 * Converts this [ProfileEntity] to an [AppProfile].
 *
 * @return A new [AppProfile] instance populated with data from this [ProfileEntity].
 */
fun ProfileEntity.toAppProfile(
): AppProfile {
    return AppProfile(
        id = mutableStateOf(this.id),
        name = mutableStateOf(this.name),
        allergens = this.allergens.toMutableList(),
        isActive = mutableStateOf(this.isActive),
    )
}